# Generated by Django 5.2.1 on 2025-06-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="authors",
            new_name="author",
        ),
    ]
